name: Build and run samples

on: [push]

jobs:
  sample-00:
    name: 00-hello_world
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: pypperoni/pypperoni
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8
    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake build-essential gcc g++ python3-dev libz-dev libssl-dev liblzma-dev libgdbm-dev
    - name: Clone Pypperoni/Python-3.6.8
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/Python-3.6.8
        path: pypperoni/python
    - name: Build Pypperoni/Python-3.6.8
      run: |
        cd pypperoni/python
        mkdir -p build/linux2
        cd build/linux2
        cmake ../..
        make -j
    - name: Clone Pypperoni/samples
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/samples
        path: pypperoni/samples
    - name: Build 00-hello_world
      run: |
        cd pypperoni/samples/00-hello_world
        python3.6 build.py
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j8
    - name: Run 00-hello_world
      run: |
        cd pypperoni/samples/00-hello_world/build
        ./00-hello_world
        cd ..
        rm -rf build

  sample-01:
    name: 01-basic
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: pypperoni/pypperoni
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8
    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake build-essential gcc g++ python3-dev libz-dev libssl-dev liblzma-dev libgdbm-dev
    - name: Clone Pypperoni/Python-3.6.8
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/Python-3.6.8
        path: pypperoni/python
    - name: Build Pypperoni/Python-3.6.8
      run: |
        cd pypperoni/python
        mkdir -p build/linux2
        cd build/linux2
        cmake ../..
        make -j
    - name: Clone Pypperoni/samples
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/samples
        path: pypperoni/samples
    - name: Build 01-basic
      run: |
        cd pypperoni/samples/01-basic
        python3.6 build.py
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j8
    - name: Run 01-basic
      run: |
        cd pypperoni/samples/01-basic/build
        ./01-basic
        cd ..
        rm -rf build

  sample-02:
    name: 02-exceptions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: pypperoni/pypperoni
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8
    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake build-essential gcc g++ python3-dev libz-dev libssl-dev liblzma-dev libgdbm-dev
    - name: Clone Pypperoni/Python-3.6.8
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/Python-3.6.8
        path: pypperoni/python
    - name: Build Pypperoni/Python-3.6.8
      run: |
        cd pypperoni/python
        mkdir -p build/linux2
        cd build/linux2
        cmake ../..
        make -j
    - name: Clone Pypperoni/samples
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/samples
        path: pypperoni/samples
    - name: Build 02-exceptions
      run: |
        cd pypperoni/samples/02-exceptions
        python3.6 build.py
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j8
    - name: Run 02-exceptions
      run: |
        cd pypperoni/samples/02-exceptions/build
        ./02-exceptions catchall
        cd ..
        rm -rf build

  sample-03:
    name: 03-async
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: pypperoni/pypperoni
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8
    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake build-essential gcc g++ python3-dev libz-dev libssl-dev liblzma-dev libgdbm-dev
    - name: Clone Pypperoni/Python-3.6.8
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/Python-3.6.8
        path: pypperoni/python
    - name: Build Pypperoni/Python-3.6.8
      run: |
        cd pypperoni/python
        mkdir -p build/linux2
        cd build/linux2
        cmake ../..
        make -j
    - name: Clone Pypperoni/samples
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/samples
        path: pypperoni/samples
    - name: Build 03-async
      run: |
        cd pypperoni/samples/03-async
        python3.6 build.py
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j8
    - name: Run 03-async
      run: |
        cd pypperoni/samples/03-async/build
        ./03-async
        cd ..
        rm -rf build

  sample-04:
    name: 04-threading
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: pypperoni/pypperoni
    - name: Set up Python 3.6.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6.8
    - name: Install dependencies
      run: |
        sudo apt-get install -y cmake build-essential gcc g++ python3-dev libz-dev libssl-dev liblzma-dev libgdbm-dev
    - name: Clone Pypperoni/Python-3.6.8
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/Python-3.6.8
        path: pypperoni/python
    - name: Build Pypperoni/Python-3.6.8
      run: |
        cd pypperoni/python
        mkdir -p build/linux2
        cd build/linux2
        cmake ../..
        make -j
    - name: Clone Pypperoni/samples
      uses: actions/checkout@v2
      with:
        repository: Pypperoni/samples
        path: pypperoni/samples
    - name: Build 04-threading
      run: |
        cd pypperoni/samples/04-threading
        python3.6 build.py
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j4
    - name: Run 04-threading
      run: |
        cd pypperoni/samples/04-threading/build
        ./04-threading
        cd ..
        rm -rf build
